# Use the official Python image from the Docker Hub
FROM python:3.12-slim

# Set the working directory
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install flask
RUN pip install numpy
RUN pip install joblib
RUN pip install scikit-learn
RUN pip install pandas

# Make port 5000 available to the world outside this container
#EXPOSE 5000

COPY . .
# Run app.py when the container launches
CMD ["python", "app.py"]



# FROM python:3.8-slim
# WORKDIR /app
# COPY requirements.txt .
# RUN pip install -r requirements.txt
# COPY . .
# CMD ["python", "app.py"]
